name: Run release!
description: Easily create releases per semantic-release
branding:
  icon: arrow-up-circle
  color: green
runs:
  using: node12
  main: dist-ncc/index.js
inputs:
  debug:
    description: debug
    default: false
  dry:
    description: Dry run
    default: false
  config:
    description: Config file (JSON or JS module) or inline config to use on top of the defaults
    required: false
  force:
    description: Force a release
